### ISSUE TITLE
Support SVG image

### ISSUE THREAD

**Issue by clawfire** [vapid/vapid#116]
**Describe the bug**
I was expected to see the file rendered.

**To Reproduce**
1. Go to any upload field and upload an SVG
2. See the preview

**Expected behavior**
SVG being rendered

**Screenshots**
![image](https://user-images.githubusercontent.com/1178/53288742-84888780-378c-11e9-95eb-1d50b10aea88.png)

**Your Environment**
 - OS: OSX
 - Browser Chrome
 - Node Version 11.6.0
 - Vapid Version 0.5.1

**Additional context**
When I check the `upload` folder I see my "svg" which was modified like ... maybe some picture transformation at some point ... 
![image](https://user-images.githubusercontent.com/1178/53288759-653e2a00-378d-11e9-84eb-59f167cff083.png)

**Comment by srobbin** [comment]
@clawfire Thanks for submitting this. I see what's happening—it's similar to an issue that a friend of mine just reported, where animated GIFs were being stripped of the animation.

The issue is being caused by [Vapid's image resizing/reorienting code](https://github.com/vapid/vapid/blob/master/lib/dashboard.js#L565-L568). I think the quick solution is to disallow resizing for SVG and animated GIFs. I'll look into it this week.

**Comment by srobbin** [comment]
@clawfire This should be fixed now in v0.7.3. To update:

`npm install -g @vapid/cli`

Let me know if you run into any troubles. And thanks again for submitting the issue.
