### ISSUE TITLE
Bug: Timestamps not working

### ISSUE THREAD

**Issue by JohJakob** [vapid/vapid#181]
The timestamp template tags `{{_created_at}}` and `{{_updated_at}}` are not working. On the rendered page, they are displayed as `{{section_name::_created_at}}` and `{{section_name::_updated_at}}`.

**To Reproduce**

1. Add `{{_created_at}}` or `{{_updated_at}}` to a `{{#section}}` block
2. Visit the rendered page

**Expected behavior**
`{{_created_at}}` should return the record’s date of creation. `{{_updated_at}}` should return the date of the record’s last edit.

**Your Environment**
 - OS: macOS Catalina 10.15.4
 - Browser: Safari 13.1
 - Node Version: 8.16.2
 - Vapid Version: 0.9.6

**Comment by srobbin** [comment]
@JohJakob Is this before or after you add posts to the section in the dashboard?

**Comment by Voydfox** [comment]
I'm having the same issue.

**Your Environment**

- OS: Windows 10
- Browser: Chrome Version 83.0.4103.61
- Node Version: 8.11.1
- Vapid Version: 9.9.6

**Comment by JohJakob** [comment]
@srobbin It happens after I add posts to the section.

**Comment by srobbin** [comment]
@JohJakob, @Voydfox Thank you. It looks like it was [a known bug with Sequelize](https://github.com/sequelize/sequelize/issues/11225#issuecomment-527405636) that had an easy workaround. Try upgrading to Vapid v0.10.0 and let me know if it's fixed.

_Note: Vapid v0.10.0 now requires Node >= v10, since Node v8 was end-of-lifed in December._

**Comment by Voydfox** [comment]
@srobbin it works, thank you kindly! <3
