### ISSUE TITLE
Create a VS Code extension to format code

### ISSUE THREAD

**Issue by asitemade4u** [vapid/vapid#23]

**Comment by srobbin** [comment]
@asitemade4u That's a great idea—I'd love to see something similar for Sublime Text. I'm planning to set up a discussion forum soon, so we can collaborate on topics like these, ones that aren't directly related to the Vapid CMS code in this repo. I'll post about it here as soon as it's ready. In the meantime, I'd recommend using a Handlebars.js extension, since Vapid's template tags are similar in structure.

**Comment by srobbin** [comment]
@asitemade4u I just set up an [online forum](https://forums.vapid.com/) for issues that aren't directly related to the Vapid CMS. If you wouldn't mind, can you please create a new thread there, about the VS Code extension (and possibly broader to include others like Sublime)? Thank you.
