### ISSUE TITLE
ImageBoss Integration?

### ISSUE THREAD

**Issue by igorescobar** [vapid/vapid#4]
Hey guys,

Question - how would be the best way to integrate https://ImageBoss.me and vapid?

Thanks!

**Comment by seanwash** [comment]
@igorescobar Seems like the easiest way would be to prepend your uploaded image urls with the imageboss url and params: https://imageboss.me/docs. You'd also want to make sure that when you use create the template tag that you set the `tag` param to false so that you get a url back instead of a full image tag: https://docs.vapid.com/content-types#image.

I haven't tested it, but maybe something like this would work:

```
<img src="https://img.imageboss.me/cover/200x200/https://yourdomain.com/{{my_image tag=false}}" />
```

It could be useful if we could access env vars so you could put your domain in an env var and not have to hard code it into a URL like that. 🤔

**Comment by srobbin** [comment]
Yeah, that's exactly what I would do too.

**Comment by igorescobar** [comment]
And this would work for layout images too? Like the ones inserted on CSS etc?

**Comment by igorescobar** [comment]
During the post creating I was wondering if we could achieve something better like:
<img src="{{my_image tag=false}}" imageboss-operation="cover"  imageboss-width="200" imageboss-height="200" /> and then during the parsing it would render the image correctly.

Would also be nice to have a way to extend the interface and have like a visual way of setting those properties.

**Comment by srobbin** [comment]
@igorescobar I just created a new issue (#57) that I think would be a good place to continue this discussion. It's a feature request for custom directives (plugins). The idea is that you'd be able to create a special content type for ImageBoss. For example:

```
{{my_image type=imageboss operation=cover width=200 height=200}}
```
Which, in the long term, might be more useful than hacking the `type=image` tag for your needs.

I'm going to close this issue, so we can consolidate the custom directive talk in #57. Please feel free to chime in there.
