### ISSUE TITLE
Websocket error on self hosting

### ISSUE THREAD

**Issue by chwzr** [vapid/vapid#75]
**Describe the bug**
I'm running a Vapid behind a Nginx Proxy.
Everything is fine, beside that the dashboards livereload script produces this error:
```
WebSocket connection to 'ws://localhost:3000/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

Maybe there should be a config var "hostname" or similar. 
I've tried ws://mydomain.com:3000/livereload and it works fine.

I think this line produces the error above: [here](https://github.com/vapid/vapid/blob/fedcaeb4ffb707489b366963e84dd7554a9af6a4/assets/dashboard/javascripts/dashboard/websocket.js#L2)

**To Reproduce**
1. install vapid
2. proxy with nginx port *:443 to localhost:3000
3. open page

**Expected behavior**
websocket working

**Comment by srobbin** [comment]
@chwzr Thanks for submitting this. It is a bug indeed.

Sounds like maybe two issues:

1. WebSocket shouldn't try to connect production mode (when `NODE_ENV=production`), since that's only relevant when you're live editing code.
2. The `ws://localhost:3000/livereload` line should derive its host from `window.location` instead of hard-coding it.

I'll work on this, and get it released shortly.

**Comment by chwzr** [comment]
thanks for the input, didn't put node in production. I think window.location will allways work, and would be a good solution!
